version: 2

updates:
  - package-ecosystem: npm
    directory: "/src"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/functions"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
